language: python
matrix:
    include:
        - os: linux
          dist: trusty
          python: 3.6
        - os: osx
          language: generic
          env: PYVERSION='3.6.0'
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated | grep -q pyenv && brew upgrade pyenv || true; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then eval "$(pyenv init -)"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv install $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv global $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv versions; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then python --version; fi
install:
  - python setup.py install
script:
  - py.test