language: python
matrix:
  include:
    - os: linux
      python: "3.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6
install:
  - python setup.py install
script:
  - py.test