language: python
python:
  - "3.6"
env:
  - MINICONDA_VERSION=latest TRAVIS_PYTHON_VERSION=3.6
os:
  - linux
  - osx
install:
  - printenv | sort
  - MINICONDA_PYVERSION=3 ;
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      MINICONDA_OS=Linux ;
    else
      MINICONDA_OS=MacOSX ;
    fi ;
    echo "Fetching Python $MINICONDA_PYVERSION miniconda for $MINICONDA_OS" ;
    wget https://repo.continuum.io/miniconda/Miniconda$MINICONDA_PYVERSION-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/bin/activate root
  - printenv | sort
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  # Use the latest conda
  - conda update conda --no-pin -q
  - if test x"$CONDA_CANARY" = xtrue ; then conda update -n root -c conda-canary conda; fi
  - if test x"$MINICONDA_VERSION" = x"4.1.11" ; then CONDA_BUILD_CONSTRAINT='=2.1.5'; else CONDA_BUILD_CONSTRAINT='' ; fi
  - conda install -n root conda-build$CONDA_BUILD_CONSTRAINT psutil
  - conda info -a
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS_PACKAGES=libffi ;
    fi ;
    conda create -q -n test-environment python="$TRAVIS_PYTHON_VERSION" anaconda $OS_PACKAGES
  - source activate test-environment
  - printenv | sort
  - unset CONDA_ENV_PATH # because the older conda in miniconda sets this, confusing some tests
  - export PATH=`echo "$PATH" | sed -e s@"$HOME"/miniconda/bin:@@g`
  - printenv | sort
  - python setup.py install
script:
  - py.test